name: 🚀 Deploy to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Hugging Face Hub
        run: pip install --upgrade huggingface_hub

    - name: Push to Hugging Face Hub
      uses: huggingface/hub-action@v1
      with:
        repo_id: "Deba4/NewSpace1"
        repo_type: space
        token: ${{ secrets.HF_TOKEN }}
